sync

diff --git a/umnt b/umnt
--- a/umnt
+++ b/umnt
@@ -2,25 +2,42 @@
 
 args=("$@")
 
-[[ -z "${args[0]}" || "${args[0]}" == "--help" ]] && echo "Options:
-- usb
-- usb2
-- ext
-- phone
---help" && exit
-
 MOUNT_DIR="$HOME/mnt"
 [ ! -d "$MOUNT_DIR" ] && echo "$MOUNT_DIR does not exist." && exit 1
 
 is_mounted() {
   mounted_device="$(lsblk -nrpo "name,type,size,mountpoint" | grep "$1")"
-  [ -z "$mounted_device" ] && echo "Device not found." && exit 1 
-  }
+  [ -z "$mounted_device" ] && echo "Device not found." && exit 1
+}
+
+unmount() {
+    is_mounted "$MOUNT_DIR/$1"
+    sudo -A umount "$MOUNT_DIR/$1"
+    echo "Device unmounted."
+}
+
+checkDir() {
+    echo -e "Dir: $MOUNT_DIR/$1\n"
+    ls --color=auto -al "$MOUNT_DIR/$1"
+}
 
 case "${args[0]}" in
-  "dev") is_mounted "$MOUNT_DIR/dev"; sudo -A umount "$MOUNT_DIR/usb";;
-  "phone") sudo fusermount -u "$MOUNT_DIR/phone";;
-  *) echo "Wrong argument.";;
+  "usb1")
+      unmount "usb1"
+      checkDir "usb1"
+      ;;
+  "usb2")
+      unmount "usb1"
+      checkDir "usb2"
+      ;;
+  "ext")
+      unmount "ext"
+      checkDir "ext"
+      ;;
+  "phone")
+      sudo fusermount -u "$MOUNT_DIR/phone"
+      ;;
+  *)
+      echo "Usage: usb1/usb2/ext/phone"
+      ;;
 esac
-
-echo "Device unmounted."
