sync

diff --git a/core/umnt b/core/umnt
--- a/core/umnt
+++ b/core/umnt
@@ -1,49 +1,31 @@
 #!/bin/sh
 
+source config
+
 args=("$@")
 
 MOUNT_DIR="$HOME/mnt"
+DEV_MOUNT_DIR="$HOME/mnt/dev"
 [ ! -d "$MOUNT_DIR" ] && echo "$MOUNT_DIR does not exist." && exit 1
 
-is_mounted() {
-  mounted_device="$(lsblk -nrpo "name,type,size,mountpoint" | grep "$1")"
-  [ -z "$mounted_device" ] && echo "Device not found." && exit 1
-}
-
-unmount() {
-    is_mounted "$MOUNT_DIR/$1"
-    sudo -A umount "$MOUNT_DIR/$1"
-    echo "Device unmounted."
-}
-
-checkDir() {
-    echo "Dir: $MOUNT_DIR/$1"
-    ls --color=auto -al "$MOUNT_DIR/$1"
-}
-
 case "${args[0]}" in
-  "usb1")
-      unmount "usb1"
-      checkDir "usb1"
-      echo
-      lsblk
-      ;;
-  "usb2")
-      unmount "usb2"
-      checkDir "usb2"
-      echo
-      lsblk
-      ;;
-  "ext")
-      unmount "ext"
-      checkDir "ext"
-      echo
+  "dev")
+      mounted_device="$(lsblk -nrpo "name,type,size,mountpoint" | grep $DEV_MOUNT_DIR)"
+      [ -z "$mounted_device" ] && echo "Device not found." && exit 1
+
+      sudo -A umount "$DEV_MOUNT_DIR"
+      echoGreen "Device unmounted."
+
+      echoBlue "Dir: $DEV_MOUNT_DIR:"
+      ls --color=auto -al "$DEV_MOUNT_DIR"
+
+      echoBlue -n "lsblk:"
       lsblk
       ;;
   "phone")
       sudo fusermount -u "$MOUNT_DIR/phone"
       ;;
   *)
-      echo "Usage: usb1/usb2/ext/phone"
+      echo "Usage: dev/phone"
       ;;
 esac
